// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPPrayerService;

namespace UPPrayerService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191008182136_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("UPPrayerService.Models.Confirmation", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Confirmations");
                });

            modelBuilder.Entity("UPPrayerService.Models.Endorsement", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonateURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomepageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Endorsements");
                });

            modelBuilder.Entity("UPPrayerService.Models.Reservation", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ConfirmationID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("UPPrayerService.Models.Reservation", b =>
                {
                    b.HasOne("UPPrayerService.Models.Confirmation", null)
                        .WithMany("Reservations")
                        .HasForeignKey("ConfirmationID");
                });
#pragma warning restore 612, 618
        }
    }
}
